import { apiClient } from '../lib/api'
import type { KpisResponse } from '../lib/apiTypes'
import type { Page } from './types'

/**
 * RoomSense Occupancy Analysis — two-act leave-behind for TU/e budget holders.
 * Act 1: Hours Wasted (ghost meetings)
 * Act 2: Seats Over-Provisioned (capacity mismatch)
 * Self-sufficient: framing metadata, recommended actions, print-friendly.
 */

function renderSkeleton(): string {
  return `
    <div class="report">
      <div id="report-content" aria-busy="true"></div>
    </div>
  `
}

function renderError(container: HTMLElement, err: unknown): void {
  const content = container.querySelector('#report-content')!
  content.innerHTML = `
    <div class="report-error">
      <p>Couldn't load report data</p>
      <p>${err instanceof Error ? err.message.replace(/[<>]/g, '') : 'Unknown error'}</p>
    </div>
  `
}

function buildingLabel(building: string): string {
  return building.charAt(0).toUpperCase() + building.slice(1)
}

function renderReport(container: HTMLElement, kpis: KpisResponse): void {
  const content = container.querySelector('#report-content')!
  content.setAttribute('aria-busy', 'false')

  const reportDate = new Date().toLocaleDateString('en-GB', {
    year: 'numeric', month: 'long', day: 'numeric'
  })

  const peakPct = kpis.totalCapacity > 0
    ? Math.round((kpis.peakConcurrentOccupancy / kpis.totalCapacity) * 100)
    : 0

  content.innerHTML = `
    <div class="report-header">
      <h1>RoomSense Occupancy Analysis</h1>
      <p class="date-range">Last 30 days · Generated ${reportDate}</p>
      <p class="report-source">TU/e campus — Atlas, Flux, Neuron | Data source: Terabee people-counting sensors (simulated; production path via IoT Hub → Databricks)</p>
    </div>

    <section class="report-act">
      <h2>Act 1: Hours Wasted</h2>
      <div class="report-metrics">
        <div class="metric">
          <div class="metric-label">Wasted Hours</div>
          <div class="metric-value">${Math.round(kpis.wastedHours ?? 0)}h</div>
          <div class="metric-note">Booked-but-empty meeting time</div>
        </div>
        <div class="metric">
          <div class="metric-label">Ghost Rate</div>
          <div class="metric-value">${(kpis.ghostRatePct ?? 0).toFixed(1)}%</div>
          <div class="metric-note">Of all booked hours</div>
        </div>
        <div class="metric">
          <div class="metric-label">Indicative Cost</div>
          <div class="metric-value">€${(kpis.wastedEur ?? 0).toFixed(0)}</div>
          <div class="metric-note">Estimated at €4/desk/hour</div>
        </div>
      </div>
    </section>

    <section class="report-act">
      <h2>Act 2: Seats Over-Provisioned</h2>
      <div class="report-portfolio">
        <p class="portfolio-headline">
          <strong>${kpis.totalCapacity ?? 0}</strong> total seats across campus.
          Peak concurrent usage: <strong>${kpis.peakConcurrentOccupancy ?? 0}</strong> people.
          That's ${peakPct}% of capacity at peak.
        </p>
      </div>
      <table class="report-capacity-table">
        <thead>
          <tr>
            <th>Room</th>
            <th>Building</th>
            <th class="num">Capacity</th>
            <th class="num">Avg During Booked Hours</th>
            <th class="num">Efficiency</th>
          </tr>
        </thead>
        <tbody>
          ${(kpis.roomBreakdown ?? []).map((room) => {
            const efficiency = room.capacity > 0
              ? Math.round((room.avgBookedOccupancy / room.capacity) * 100)
              : 0
            return `
              <tr>
                <td>${room.name}</td>
                <td>${buildingLabel(room.building)}</td>
                <td class="num">${room.capacity}</td>
                <td class="num">${room.avgBookedOccupancy.toFixed(1)}</td>
                <td class="num">${efficiency}%</td>
              </tr>
            `
          }).join('')}
        </tbody>
      </table>
    </section>

    <section class="report-recommendations">
      <h2>Recommended Actions</h2>
      <ol>
        <li>Audit repeat ghost bookings — ${Math.round(kpis.wastedHours ?? 0)} hours/month of booked-but-empty time is recoverable through booking discipline.</li>
        <li>Assess whether large rooms (80+ seats) are right-sized for typical demand. Average occupancy during booked hours indicates actual need.</li>
        <li>Consider reallocating underused large spaces into smaller focus pods where peak demand suggests higher small-room utilization.</li>
      </ol>
    </section>

    <footer class="report-footer">
      <p>Generated by RoomSense for TU/e campus operations review.</p>
    </footer>
  `
}

export const reportPage: Page = {
  async mount(container: HTMLElement) {
    container.innerHTML = renderSkeleton()
    try {
      const kpis = await apiClient.getKpis()
      renderReport(container, kpis)
    } catch (err) {
      renderError(container, err)
    }
  },
}
